### ISSUE TITLE
Limitations when using the repository

### ISSUE THREAD

**Issue by AdrianPrados** [ir-lab/bimanual-imitation#2]
Hello,

We are trying to use your work for our own model but we are encountering some issues. First, we want to load our robot directly from a URDF file that we have set up. I see that your work uses an XML file to load the dual manipulator. Is there an easy way to load our robot into the simulator?

On the other hand, we noticed that in the previous implementation (https://github.com/ir-lab/irl_control/tree/master), there were scripts that are not present in this new implementation (PID Gain test, Forces Test, etc.). Is there a way to use these scripts with the new implementation of this repository?

Best regards, and I look forward to your response.

**Comment by mdrolet01** [comment]
Hello,

As far as I am aware, URDF models are not directly importable to mujoco. You'll probably need to manually create the XML file, which can be time-consuming. There may be tools to convert to mujoco XML, but I'm not sure how reliable they are.

The scripts in the old repo used mujoco-py but I don't plan on adding them to this repo (which uses the mujoco API). If you are interested, you can check out the move_to_point example in this repo to get a gist of how to set up the environment in the same way. Then you can copy over + change a few lines of code from the previous script (since only the API has changed and nothing else). However note that we implicitly control the base in this OSC, so the PID gain test will not behave the same as in the GIFs in the IRL Control repo (which was generated using explicit base control).

Best,
Michael
